# Auto-generated by compose2nix.

{ pkgs, lib, config, secrets, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."sure-db" = {
    image = "postgres:16";
    environment = {
      "POSTGRES_DB" = "sure_production";
      "POSTGRES_PASSWORD" = "sure_password";
      "POSTGRES_USER" = "sure_user";
    };
    volumes = [
      "sure_postgres-data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
      "--health-interval=5s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=sure_sure_net"
    ];
  };
  systemd.services."podman-sure-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-sure_sure_net.service"
      "podman-volume-sure_postgres-data.service"
    ];
    requires = [
      "podman-network-sure_sure_net.service"
      "podman-volume-sure_postgres-data.service"
    ];
    partOf = [
      "podman-compose-sure-root.target"
    ];
    wantedBy = [
      "podman-compose-sure-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sure-redis" = {
    image = "redis:latest";
    volumes = [
      "sure_redis-data:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"redis-cli\", \"ping\"]"
      "--health-interval=5s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=redis"
      "--network=sure_sure_net"
    ];
  };
  systemd.services."podman-sure-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-sure_sure_net.service"
      "podman-volume-sure_redis-data.service"
    ];
    requires = [
      "podman-network-sure_sure_net.service"
      "podman-volume-sure_redis-data.service"
    ];
    partOf = [
      "podman-compose-sure-root.target"
    ];
    wantedBy = [
      "podman-compose-sure-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sure-web" = {
    image = "ghcr.io/we-promise/sure:stable";
    environment = {
      "AI_RESPONSE_TIMEOUT" = "90";
      "ASSISTANT_MAX_TOOL_CALL_ITERATIONS" = "";
      "DB_HOST" = "db";
      "DB_PORT" = "5432";
      "LLM_CONTEXT_WINDOW" = "";
      "OPENAI_ACCESS_TOKEN" = "";
      "OPENAI_MODEL" = "";
      "OPENAI_REQUEST_TIMEOUT" = "60";
      "OPENAI_URI_BASE" = "";
      "POSTGRES_DB" = "sure_production";
      "POSTGRES_PASSWORD" = "sure_password";
      "POSTGRES_USER" = "sure_user";
      "RAILS_ASSUME_SSL" = "false";
      "RAILS_FORCE_SSL" = "false";
      "REDIS_URL" = "redis://redis:6379/1";
      "SECRET_KEY_BASE" = secrets.sure.secretkey;
    };
    volumes = [
      "sure_app-storage:/rails/storage:rw"
    ];
    ports = [
      "3000:3000/tcp"
    ];
    dependsOn = [
      "sure-db"
      "sure-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--dns=1.1.1.1"
      "--dns=8.8.8.8"
      "--network-alias=web"
      "--network=sure_sure_net"
    ];
  };
  systemd.services."podman-sure-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-sure_sure_net.service"
      "podman-volume-sure_app-storage.service"
    ];
    requires = [
      "podman-network-sure_sure_net.service"
      "podman-volume-sure_app-storage.service"
    ];
    partOf = [
      "podman-compose-sure-root.target"
    ];
    wantedBy = [
      "podman-compose-sure-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sure-worker" = {
    image = "ghcr.io/we-promise/sure:stable";
    environment = {
      "AI_RESPONSE_TIMEOUT" = "90";
      "ASSISTANT_MAX_TOOL_CALL_ITERATIONS" = "";
      "DB_HOST" = "db";
      "DB_PORT" = "5432";
      "LLM_CONTEXT_WINDOW" = "";
      "OPENAI_ACCESS_TOKEN" = "";
      "OPENAI_MODEL" = "";
      "OPENAI_REQUEST_TIMEOUT" = "60";
      "OPENAI_URI_BASE" = "";
      "POSTGRES_DB" = "sure_production";
      "POSTGRES_PASSWORD" = "sure_password";
      "POSTGRES_USER" = "sure_user";
      "RAILS_ASSUME_SSL" = "false";
      "RAILS_FORCE_SSL" = "false";
      "REDIS_URL" = "redis://redis:6379/1";
      "SECRET_KEY_BASE" = secrets.sure.secretkey;
      "SELF_HOSTED" = "true";
    };
    volumes = [
      "sure_app-storage:/rails/storage:rw"
    ];
    cmd = [ "bundle" "exec" "sidekiq" ];
    dependsOn = [
      "sure-db"
      "sure-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--dns=1.1.1.1"
      "--dns=8.8.8.8"
      "--network-alias=worker"
      "--network=sure_sure_net"
    ];
  };
  systemd.services."podman-sure-worker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-sure_sure_net.service"
      "podman-volume-sure_app-storage.service"
    ];
    requires = [
      "podman-network-sure_sure_net.service"
      "podman-volume-sure_app-storage.service"
    ];
    partOf = [
      "podman-compose-sure-root.target"
    ];
    wantedBy = [
      "podman-compose-sure-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-sure_sure_net" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f sure_sure_net";
    };
    script = ''
      podman network inspect sure_sure_net || podman network create sure_sure_net --driver=bridge
    '';
    partOf = [ "podman-compose-sure-root.target" ];
    wantedBy = [ "podman-compose-sure-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-sure_app-storage" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect sure_app-storage || podman volume create sure_app-storage
    '';
    partOf = [ "podman-compose-sure-root.target" ];
    wantedBy = [ "podman-compose-sure-root.target" ];
  };
  systemd.services."podman-volume-sure_postgres-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect sure_postgres-data || podman volume create sure_postgres-data
    '';
    partOf = [ "podman-compose-sure-root.target" ];
    wantedBy = [ "podman-compose-sure-root.target" ];
  };
  systemd.services."podman-volume-sure_redis-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect sure_redis-data || podman volume create sure_redis-data
    '';
    partOf = [ "podman-compose-sure-root.target" ];
    wantedBy = [ "podman-compose-sure-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-sure-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
